name             'jenkins-java'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jenkins-java'
long_description 'Installs/Configures jenkins-java'
version          '0.1.0'

depends 'java'
depends 'jenkins'